### ISSUE TITLE
How to cancel automatic analysis

### ISSUE THREAD

**Issue by hksoobe** [MahdiSafsafi/UnivDisasm#11]
for example
![image](https://cloud.githubusercontent.com/assets/6091308/15036890/f94b3fbe-12c7-11e6-8b67-74ccf4bf625a.png)
used UnivDisasm-master\Examples\Demo1
/\* testfun _/
0067B508 call @0x401004
0067B50E jmp @0x401004
0067B514 ret
/_------------------------------------------------*/
I just need the original instruction

What should I do? thank you!

In addition to this problem:
https://github.com/MahdiSafsafi/UnivDisasm/issues/10

**Comment by MahdiSafsafi** [comment]
Remove USO_SHOW_DST_ADDR option from SyntaxOptions and UnivDisasm will display the original memory.
`ins.SyntaxOptions := (USO_DEFAULT or USO_SHOW_PTR) and not USO_SHOW_DST_ADDR;`
