### ISSUE TITLE
Can you add an option number uppercase?

### ISSUE THREAD

**Issue by hksoobe** [MahdiSafsafi/UnivDisasm#13]
call @00ada72f
to
call @00ADA72F

add esp,0xf0
to
add esp,0xF0

and can you  add the display options for the @ symbol？

This looks more align

Thank you!

**Comment by MahdiSafsafi** [comment]
Hi,
Sorry for being late to answer
@ sign is used to indicate that the address was decoded (the call will go to that address). I prefer to let this symbol.
For numbers, I believe that it's better to keep them as mnemonics case state.
If you don't feel confortable with UNIV Syntax, you may think to customize UNIV_SYNTAX and register a new syntax decoder.
