### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by hksoobe** [MahdiSafsafi/UnivDisasm#14]
55            push ebp
8B EC       mov ebp,esp
83 C4 F8  add esp,0xfffffffffffffff8   <-----error
53            push ebx
56            push esi

The previous version does not have this error

**Comment by MahdiSafsafi** [comment]
Hey hksoobe !

That's not a bug ! UnivDisasm syntax uses Imm64 type mostly in all situations ! 
```83 C4 F8``` is equivalent to : ```add esp, -8``` which equals to : ```add esp, 0xf8``` when using Imm8 type.
```0xfffffffffffffff8``` is the hex representation of (-8) as Imm64.
If you don't like it, you can easy build your own syntax based on UnivSyntax !

Regards,
Mahdi.

**Comment by hksoobe** [comment]
thank you
