### ISSUE TITLE
Your disassembly engine (UnivDisasm) intend to support ARM?

### ISSUE THREAD

**Issue by hksoobe** [MahdiSafsafi/UnivDisasm#16]
Your disassembly engine (UnivDisasm) developed very well, but if it can support ARM better

**Comment by MahdiSafsafi** [comment]
Hi hksoobe,
Yes there is a plan to add ARM(AArch32 && AArch64) support. I already published [Azote](https://github.com/MahdiSafsafi/Azote) as AArch64 disassembler. 
Internally, the project is on active development and for now I'm working to generate a better `A32|T16|T32|A64` opcodes map.
