### ISSUE TITLE
invalid Pathes

### ISSUE THREAD

**Issue by Memnarch** [MahdiSafsafi/UnivDisasm#3]
Currently, only the includefiles are copied. For the source_folder, simply remove the include subdirectory. (Base only states that the base-directory is removed from the targetpath, which means instead of creating the structure Source\Includes at the destination, it will create \Includes)

same goes for the search- and browsing-paths. You told the setup to copy all files relative to the path after Source. The Search- and Browsing-Pathes are relative to the components source-folder. In your case this would result in something like:

<ComponentInstallDirectory>\Source\Source
<ComponentInstallDirectory>\Source\Source\Include

You can simply remove the source folder from the Search- and Browsing-Pathes

**Comment by MahdiSafsafi** [comment]
Thank you Memnarch for your feedback.

So this: "pathes": "Source;Source\Includes" should be transformed to : "pathes": "Source\Includes" ?

Mahdi.

**Comment by Memnarch** [comment]
you can strip the source in front of the include aswell. The filecopy algorythm goes like this:

Folder structure in your repo:
Source\FolderA
Source\FolderC\FolderD
Base specified: Source
Structure that is created by the algorythm in the targetdirectory:
FolderA
FolderC\FolderD

So pathes should be transformed to:
".;Includes"

The dot is a symbol which means the current directory (which is the sourcedirectory of the installed component) and then "Includes" to tell it to use the Includes-subdirectory folder, too.
If you had a folder in Includes you wanted to, you'd add the path "Includes\MyOtherFolder", too. It's all relative :)

**Comment by Memnarch** [comment]
you have to know, everytime you install a package, a subdirectory with the packagename is created. This directory has these defaultsubfolders:

Bin (here there goes exe, dlls and stuff)
Lib (DCUs compiled during installation if packages or other projects exists)
Source (Thats the folder where it copies your sourcefiles, to)

**Comment by MahdiSafsafi** [comment]
So , will this solve the problem ?
//-----------------------------------------
{
        "search_pathes": 
    [
        {
            "pathes": ".;Includes",
            "platforms": "Win32;Win64;OSX32"
        }
    ],
    "browsing_pathes": 
    [
        {
            "pathes": ".;Includes",
            "platforms": "Win32;Win64;OSX32"
        }
    ],

```
"source_folders":
[
    {
        "folder": "Source",
        "base": "Source",
        "recursive": true,
        "filter": "*;*.*"
    }
]
```

}

**Comment by Memnarch** [comment]
Yes this should do the trick. And sorry for the late Reply, was on a festival.

**Comment by MahdiSafsafi** [comment]
It's okay don't worry..
And it's nice to hear that you got some fun for yourself.
